### Create User (dyn)
POST http://localhost:3000/dyn/users
Content-Type: application/json

{
    "name": "test122"
}


### Get Users Paginated (dyn)
GET http://localhost:3000/dyn/users?page=0&rpp=5


### Get User with id (dyn)
GET http://localhost:3000/dyn/users/1

### Create User (generic)
POST http://localhost:3000/generic/users
Content-Type: application/json

{
    "name": "test122"
}


### Get Users Paginated (generic)
GET http://localhost:3000/generic/users?page=0&rpp=5


### Get User with id (generic)
GET http://localhost:3000/generic/users/1
